name: Simple Firebase Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        # এখানে --project dev-nazrul যোগ করা হয়েছে
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --only hosting --project dev-nazrul
