name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main  # আপনার মেইন ব্রাঞ্চের নাম যদি master হয় তবে এখানে master লিখবেন

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN }}' # আমরা যেটা সেভ করেছি
          channelId: live
          projectId: dev-nazrul # আপনার ফায়ারবেস প্রোজেক্ট আইডি
